/**
 * @self-intro-quiz/shared — 共有パッケージのバレルエクスポート
 *
 * 型定義・定数・バリデーションスキーマ・イベント名を一元管理。
 * server / client 両方がこのパッケージに依存する。
 */

// 型定義
export type {
    Profile,
    ProfileFieldDefinition,
    RoomPhase,
    AnimationThemeName,
    Participant,
    Room,
    QuestionType,
    Question,
    Answer,
    ScoreEntry,
    QuizHighlight,
    ParticipantAnswerResult,
    QuestionResultSummary,
    Quiz,
    RoomStateSync,
    ParticipantInfo,
    CurrentQuestionInfo,
    RevealedAnswerInfo,
    SelfInfo,
    RoomCreatedPayload,
    RoomJoinedPayload,
    ParticipantJoinedPayload,
    ParticipantLeftPayload,
    HostChangedPayload,
    ProfileUpdatedPayload,
    QuizGeneratingPayload,
    QuizReadyPayload,
    QuizGenerateFailedPayload,
    QuestionStartPayload,
    AnswerCountPayload,
    QuestionRevealPayload,
    QuizFinishedPayload,
    RoomErrorPayload,
    CreateRoomPayload,
    JoinRoomPayload,
    SubmitProfilePayload,
    SubmitAnswerPayload,
    RoomSummary,
    RoomSummaryParticipant,
    RoomListPayload,
    CheckNicknamePayload,
    NicknameResultPayload,
    UpdateFieldsPayload,
    FieldsUpdatedPayload,
    InterviewSpeechInfo,
    InterviewStartPayload,
    VoteCuriousPayload,
    AIRequestStartedPayload,
    AIRequestSubmitPayload,
    AIRequestFinalizePayload,
    AIRequestStatusPayload,
    AIRequestResultPayload,
    AIRequestAdoptPayload,
    AIRequestCancelledPayload,
    SendInvitePayload,
    InvitationReceivedPayload,
    ProfileFieldPreset,
    ProfileFieldPresetId,
    ReactionType,
    ReactionDefinition,
    SendReactionPayload,
    ReactionReceivedPayload,
} from "./types/index.js";

// 定数
export {
    MAX_PARTICIPANTS,
    DEFAULT_MIN_PARTICIPANTS,
    ROOM_CODE_LENGTH,
    ROOM_CODE_CHARSET,
    DEFAULT_ROOM_TIMEOUT_MS,
    ROOM_CLEANUP_INTERVAL_MS,
    TOTAL_QUESTIONS,
    MIN_QUESTIONS,
    MAX_QUESTIONS,
    YES_NO_RATIO,
    DEFAULT_QUESTION_TIME_LIMIT_MS,
    MAX_CHOICES,
    YES_NO_CHOICES,
    YES_NO_QUESTION_COUNT,
    FOUR_CHOICE_QUESTION_COUNT,
    SCORE_PER_CORRECT,
    BASE_CORRECT_SCORE,
    MAX_SPEED_BONUS,
    STREAK_MULTIPLIERS,
    MAX_PROFILE_FIELD_LENGTH,
    MIN_PROFILE_FILLED_FIELDS,
    MIN_PROFILE_FIELDS,
    MAX_PROFILE_FIELDS,
    MAX_PROFILE_FIELD_LABEL_LENGTH,
    MAX_PROFILE_FIELD_PLACEHOLDER_LENGTH,
    DEFAULT_PROFILE_FIELDS,
    PROFILE_FIELDS,
    MIN_NICKNAME_LENGTH,
    MAX_NICKNAME_LENGTH,
    AI_MAX_TOKENS,
    AI_MAX_RETRIES,
    AI_RETRY_BASE_DELAY_MS,
    INTERVIEW_SPEECH_DURATION_MS,
    CURIOUS_VOTE_THRESHOLD,
    RATE_LIMIT_JOIN_PER_MIN,
    RATE_LIMIT_HTTP_PER_MIN,
    RATE_LIMIT_WINDOW_MS,
    DISCONNECT_REMOVE_TIMEOUT_MS,
    AI_REQUEST_PRESETS,
    AI_REQUEST_DISPLAY_COUNT,
    AI_REQUEST_MAX_FREE_TEXT,
    AI_REQUEST_TIMEOUT_MS,
    ANIMATION_THEMES,
    DEFAULT_ANIMATION_THEME,
    ANIMATION_THEME_META,
    INVITE_MAX_MESSAGE_LENGTH,
    INVITE_COOLDOWN_MS,
    INVITE_BANNER_AUTO_DISMISS_MS,
    REACTION_RATE_LIMIT,
    REACTION_RATE_WINDOW_MS,
    REACTION_PARTICLE_DURATION_MS,
    REACTION_MAX_VISIBLE,
    DEFAULT_EMOJI_REACTIONS,
    DEFAULT_TEXT_REACTIONS,
    THEME_REACTIONS,
    REACTION_ID_MAX_LENGTH,
} from "./constants.js";

// プロフィール項目プリセット
export { PROFILE_FIELD_PRESETS, getPresetById } from "./profileFieldPresets.js";

// クイズ問題数計算
export { calculateQuizCount } from "./quizCount.js";
export type { QuizCountConfig } from "./quizCount.js";

// イベント名
export {
    C2S_EVENTS,
    S2C_EVENTS,
} from "./events.js";
export type { C2SEventName, S2CEventName } from "./events.js";

// バリデーションスキーマ
export {
    NicknameSchema,
    RoomCodeSchema,
    ProfileFieldSchema,
    ProfileFieldDefinitionSchema,
    ProfileSchema,
    createProfileSchema,
    UpdateFieldsSchema,
    CreateRoomSchema,
    JoinRoomSchema,
    SubmitProfileSchema,
    CheckNicknameSchema,
    SubmitAnswerSchema,
    VoteCuriousSchema,
    SetThemeSchema,
    AIQuestionSchema,
    AIOutputSchema,
    AIOutputJsonSchema,
    createAIOutputSchema,
    AIRequestSubmitSchema,
    AIRequestAdoptSchema,
    SendInviteSchema,
    SendReactionSchema,
} from "./validation.js";
export type {
    NicknameInput,
    RoomCodeInput,
    ProfileInput,
    CreateRoomInput,
    JoinRoomInput,
    SubmitProfileInput,
    CheckNicknameInput,
    SubmitAnswerInput,
    AIQuestionOutput,
    AIOutput,
} from "./validation.js";
